### ISSUE TITLE
Split project in several maven modules!

### ISSUE THREAD

**Issue by hansgru** [mirage-sql/mirage#30]
Split the project in several maven modules (and jars).
It would allow an easier reuse of the different parts of Mirage SQL, and also easier to extend.

E.g. there's stuff not needed at runtime, or not by  everybody, but still gets deployed since it's there in the same JAR:
- test
- integration(s)
- tools/ant/updater

and other parts that would be reusable outside of Mirage like:
- SQL parser

**Comment by aadrian** [comment]
This would be easier if the build would be migrated to Gradle.

**Comment by aadrian** [comment]
For now the project was split in:
1. **Mirage-SQL** - `miragesql-2.1.0.jar` - the core functionality
 2. **Mirage-SQL Test** - `miragesql-test-2.1.0.jar` - the testing functionality - https://github.com/mirage-sql/mirage-test
 3. **Mirage-SQL Integration** - `miragesql-integration-2.1.0.jar` - the integration with Spring, Guice and Seasar2 - https://github.com/mirage-sql/mirage-integration
