### ISSUE TITLE
Update group id

### ISSUE THREAD

**Issue by takezoe** [mirage-sql/mirage#42]

**Comment by takezoe** [comment]
@aadrian package name hasn't been updated to `com.miragesql`.

**Comment by aadrian** [comment]
> package name hasn't been updated to com.miragesql.

Not in the sources, only in the mvn descriptor for now.

Since changing the sources would break existing software, there should be a **major** not *minor* version update for this, and I would like to write a Migration Guide first.

**Comment by aadrian** [comment]
@takezoe a first version of the Migration Guide:  https://github.com/mirage-sql/mirage/wiki/Migration-Guide

**Comment by takezoe** [comment]
@aadrian Thanks. I felt 2 step migration might be redundant. How about updating to 2.0.0 directly, not through 1.3.x?

**Comment by aadrian** [comment]
Well, I already updated libraries and Java to 8 for 1.3.0 (so it's not just a version bump) and I'm in the process of aquiring a Nexus ORG for com.sqlmirage (since it can't publish to the old one).

The 1.3.0 might redundant but it's a simple drop in replacement as opposed to 2.0.0 that requires user code changes since imports must be updated too.

**Comment by takezoe** [comment]
> Well, I already updated libraries and Java to 8 for 1.3.0 (so it's not just a version bump) and I'm in the process of aquiring a Nexus ORG for com.sqlmirage (since it can't publish to the old one): https://issues.sonatype.org/browse/OSSRH-30759

Thanks. Do you mean we will continue to maintain 1.3.x for existing users who can't move to 2.0.0? That's reasonable. I will update the subject of this issue to just "Update group id" and close again.

and `1.x` branch may be confusing a little, because 1.3.0 is not on `1.x` branch.

**Comment by aadrian** [comment]
> Do you mean we will continue to maintain 1.3.x for existing users who can't move to 2.0.0? 

Yes, for a while. There are many extensions (priavate) that depend on the old package naming so keeping that for a while (until the project is split in modules at least) makes sense IMHO.

> and naming of 1.x branch may be confusing a little

Indeed. I'll delete it and when 2.0.0 will be out, I'll make a new branch: 1.3.x

**Comment by takezoe** [comment]
Thanks. All became clear.
