### ISSUE TITLE
Mirage-SQL 2.0.x

### ISSUE THREAD

**Issue by ahamana** [mirage-sql/mirage#44]
Could you tell me when the Mirage-SQL 2.0.x is released?

**Comment by aadrian** [comment]
@ahamana The plan for the 2.0 release is the next weekend (29 - 30 July).

**Comment by ahamana** [comment]
@aadrian Many thanks for your quick reply.

**Comment by ahamana** [comment]
If the plan for the 2.0 release has been fixed, could you tell me it?

**Comment by takezoe** [comment]
@aadrian Any remaining tasks for 2.0? Can we release it?

**Comment by aadrian** [comment]
@takezoe @ahamana I'm very sorry for the long delay :( .

I just published v2.0.0 and tagged it: https://github.com/mirage-sql/mirage/releases/tag/2.0.0

The release of the artifacts to Maven Central might take a while, so when they're up, I'll update the [README.md](https://github.com/mirage-sql/mirage/blob/master/README.md) with this new version too.

**Comment by aadrian** [comment]
@takezoe @ahamana the new version 2.0.0 is already in JCenter, so it can be used from any Gradle project.

**Comment by ahamana** [comment]
@takezoe @aadrian Many thanks for your quick reply and the v2.0.0 release.

**Comment by aadrian** [comment]
@ahamana please be aware of the breaking changes https://github.com/mirage-sql/mirage/wiki/Migration-Guide#migrating-from-mirage-130-to-20x  

This version is not a drop-in replacement for 1.3.0

**Comment by ahamana** [comment]
@aadrian I have already done the migration steps. Many thanks for your kind support.
