### ISSUE TITLE
Mirage for other languages too?

### ISSUE THREAD

**Issue by hansgru** [mirage-sql/mirage#5]
The idea of Mirage and the problem it solves is simply fantastic.
It's just a pity that most users don't get it, and your project is not very well known (maybe some better docs could help ?).

Another option would be to have it not just in Java, but in other languages too, at least the part with prepared statement variable handling.

**Comment by aadrian** [comment]
Groovy specific stuff will be here: https://github.com/mirage-sql/mirage-groovy
