### ISSUE TITLE
Mirage-SQL 2.1.0

### ISSUE THREAD

**Issue by ahamana** [mirage-sql/mirage#59]
The version 2.1.0 is written on the README, but it has not been published.
If the release schedule has been planed, could you please let me know it?

**Comment by aadrian** [comment]
@ahamana the readme was merged too early (but for all new modules). The plan is:
https://github.com/mirage-sql/mirage/milestones

The changes so far:
https://github.com/mirage-sql/mirage/wiki/Releases

**Comment by ahamana** [comment]
@aadrian Many thanks for the info.

**Comment by ahamana** [comment]
If the release schedule has been planed, could you please let me know?

**Comment by aadrian** [comment]
@ahamana unfortunately the new experimental "Map as Entity" functionality: https://github.com/mirage-sql/mirage/commit/b20b020a70e2252ffb764a3f86f3b04b23440e89 is still buggy, so I delayed the release :( .

I still hope to have it working and make a release this month.

**Comment by ahamana** [comment]
@aadrian Thanks for your quick reply, I see.

**Comment by ahamana** [comment]
@aadrian Is "Map as Entity" functionality still buggy?

**Comment by aadrian** [comment]
@ahamana unfortunately it still is :(  . 
Sorry but I haven't made any relevant progress on this issue yet :( .

I'm trying now to implement it as a separate feature however.

**Comment by ahamana** [comment]
@aadrian Many thanks for your quick reply. I'm looking forward to use the new version.

**Comment by takezoe** [comment]
@ahamana I will release the current master as 2.1.0.

**Comment by ahamana** [comment]
@takezoe Thanks for releasing the new version!
